# This is a basic workflow to help you get started with Actions

name: data-cleanup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  
  #            ┌───────────── minute (0 - 59)
  #            │ ┌───────────── hour (0 - 23)
  #            │ │ ┌───────────── day of the month (1 - 31)
  #            │ │ │ ┌───────────── month (1 - 12)
  #            │ │ │ │ ┌───────────── day of the week (0 - 6)
  #            │ │ │ │ │                                   
  #            │ │ │ │ │
  #            │ │ │ │ │
  #            * * * * *
  #schedule:
    # Example: Do things every 5 minutes
    #- cron: "*/5 * * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Fetch Clarity API data and save as CSV
      - name: Build + run clarityfetch image (Fetch Clarity API data and save as CSV)
        run: docker compose run -e CLARITY_API_KEY=${{ secrets.CLARITY_API_TOKEN }} --build clarityfetch
      # Currently save as intermediary CSV within container: /usr/app/raw.csv

      # TODO: decide which metrics are important to preserve/display

      # TODO: Run secondary container for R script(s), mount/read /usr/app/raw.csv
      # TODO: Run data cleanup, QA/QI, postprocessing, etc
      # TODO: Alternatively, run Rscript from Python (instead of secondary image?)
      #- name: Build claritydatacleanup image (R? Run data cleanup / postprocessing on Clarity CSV data))
      #  run: docker compose run --build claritydatacleanup

      # TODO: Store cleaned data somewhere the frontend can fetch it (S3, MinIO, Git LFS, etc)

      # ...    ...    ...    ...    ...    ...

      # TODO: implement as post step? see https://github.com/marketplace/actions/run-and-post-run-action
      - name: Delete clarityfetch + claritydatacleanup images
        run: docker rmi -f clarityfetch
