# This workflow will fetch air quality sensor data from the Clarity REST API v2,
# run cleanup operations on this data, and then merge it into a running Parquet dataset
# in our S3 bucket

# When this runs, it will fetch Recent Measurements (per-minute data) for the past ~3 hours
# Specifically it will find the beginning of the current hour then rewind 3 hours, and fetch everything that has happened since then.

# This pulls from Clarity's Fast cache, which may contain only ~24 hour of cached per-minute data.

name: recent

# Controls when the workflow will run
on:
  #            ┌───────────── minute (0 - 59)
  #            │ ┌───────────── hour (0 - 23)
  #            │ │ ┌───────────── day of the month (1 - 31)
  #            │ │ │ ┌───────────── month (1 - 12)
  #            │ │ │ │ ┌───────────── day of the week (0 - 6)
  #            │ │ │ │ │                                   
  #            │ │ │ │ │
  #            │ │ │ │ │
  #            * * * * *
  # Enable the pipeline again after testing
  schedule:
    # Run every 20 minutes to refresh data
    - cron: "*/20 * * * *"
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pipeline"
  # This allows us to share storage between the different stages of the pipeline
  pipeline:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so our job can access it
      - uses: actions/checkout@v4

      # Login to GHCR.io to pull our pre-built Docker image
      - name: Log in to GHCR.io
        uses: docker/login-action@v3
        with:
          # Authenticate using the built-in GITHUB_TOKEN
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Copy default envvar parameters for base config
      - name: Create base parameters
        run: cp .env.example .env

      # Fetch Clarity API data and save raw files locally
      - name: Fetch Clarity sensor data, clean CSV data, merge into Parquet dataset
        run: docker compose run --remove-orphans -e CLARITY_API_KEY=${{ secrets.CLARITY_API_TOKEN }} -e S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }} -e S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }} aq --recent --fetch --merge --clean

